oauth:
  properties:
    github:
      client-id: ${GITHUB_CLIENT_ID}
      client-secret: ${GITHUB_CLIENT_SECRET}
      redirect-uri: ${GITHUB_REDIRECT_URI}
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user
